import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
// import useAuth from "../hooks/useAuth";

const Home: NextPage = () => {
  // const { user, loading } = useAuth();

  // if (loading) return( "Loading ...");

  return (
    <div className="relative h-screen">
      <Head>
        <title>The Perfect Mentor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  );
};

export default Home;
