import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";


const Home: NextPage = () => {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center py-2" >
      <Head>
        <title>The Perfect Mentor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">The Perfect Mentor App</h1>
    </div>
  );
};

export default Home;
