import Head from "next/head";
import Image from "next/image";
import React from "react";
import doodle from "../public/assets/doodle.png"

const Login = () => {
  return (
    <div>
      <Head>
        <title>The Perfect Mentor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image src={doodle} alt=''/>
    </div>
  );
};

export default Login;
